AdvancedThreatAnalytics/threat-analytics-search

- background.js
- manifest.json
> Issue #35 - Fix how URLs are build when a Group menu item is clicked

- webpack.config.js
> Issue #30 - Enable 'split chunks' on Webpack for prevent duplicated code

- src/background.js
This PR fixes issue #35 (already fixed on `main`) on the `develop` branch
> Merge 'main' into 'develop'

- package.json
- src/migration.html
- src/options.html
- src/postHandler.html
- src/views/settings.html
- webpack.config.js
- yarn.lock
> Issue #30 - Split entry files into chunks (except for the background file)

- src/js/options.js
- src/views/providers.html
> Gray out disable groups instead of line-through

- src/options.html
- src/views/providers.html
- src/views/settings.html
> Add icon with buttons

- .gitignore
- README.md
- package.json
- yarn.lock
> Feature #11 - Command to zip dist folder

- src/js/shared/config_file.js
> Issue #6 - Initialize new options when parsing a Configuration File

- src/background.js
- tests/unit/background.spec.js
- tests/unit/configFile.spec.js
- tests/unit/contextMenu.spec.js
> Issue #69 - Add unit tests for contextual menu

- src/js/shared/config_file.js
- tests/unit/configFile.spec.js
> Issue #67 - Add unit tests for sanitizeSettings

- src/background.js
- src/js/migration.js
Fixes #81 
I couldn't reproduce the case Vasu told. Just made it open welcome page only installed for the first time
> Issue #81 - fix open welcome page

- src/background.js
- tests/unit/background.spec.js
> Issue #89 - Add unit test for onAlarm listener

- src/js/shared/config_file.js
- tests/unit/configFile.spec.js
> Issue #94 - improve how groups name is imported

- tests/unit/contextMenu.spec.js
> Issue #90 - test search result options

- tests/e2e/options.spec.js
> Issue PIX-311 - e2e test for example link

- .eslintrc.json
- package.json
- yarn.lock
> Issue #120 - fix eslint error

- settings.json
Fixes #132  pix-578
For QA: https://run.mocky.io/v3/c13db78d-a6a3-478a-a304-2ddf71ec85df this is the sample mock settings to fetch the data
> pix-578 #132 update settings.json

- settings.json
> pix-578 #132 update settings.json for main

- src/components/options/providers/add.svelte
- src/components/options/providers/contextMenuItems.svelte
- src/js/options.js
Fixes #150 PIX-697 
Also removed unnecessary code from `options.js` which somehow appeared again
> Issue #150 - Remove unnecessary code

- src/components/options/providers/contextMenuItems.svelte
- src/js/shared/misc.js
> Issue PIX-827 - Add validation to context menu items

- src/components/options/shared/field.svelte
- src/components/options/shared/fields.svelte
- src/js/shared/config_file.js
- src/js/shared/constants.js
- src/js/shared/misc.js
> Issue #157 - Add validation to configuration file options

- src/components/options/main.svelte
- src/components/options/providers/contextMenuItems.svelte
- src/components/options/providers/groups.svelte
- src/components/options/providers/main.svelte
> Issue #154 - Add validation to groups

- src/components/options/providers/add.svelte
- src/js/shared/misc.js
> Issue #155 - Add validation to add search providers

- src/components/options/providers/contextMenuItems.svelte
resolves: #165
resolves: PIX-850
While working on this issue, I noticed one console error also that occurs when validating any field which has errors. Created issue #167 
> Unchecked runtime.lastError: All menu items except for separators must have a title
> Issue #165 - Validate items from "Manage Context Menu" at start

- src/background.js
- src/components/options/providers/contextMenuItems.svelte
> PIX-167 | Do not add empty titles in context menu

- src/components/options/special/queries.svelte
> Issue #158 - Improve validation on Queries inputs

- src/components/options/providers/add.svelte
- src/components/options/providers/contextMenuItems.svelte
- src/components/options/special/queries.svelte
- src/js/shared/misc.js
Query does not support `TESTB64SEARCH`
resolves: #174
resolves: PIX-934
> Issue #174 | Show warning if Link/Query does not contains TESTSEARCH

- src/components/options/providers/contextMenuItems.svelte
- src/components/options/special/queries.svelte
> Issue #177 | Do not show warning if query/link is searchable

- src/components/options/providers/contextMenuItems.svelte
> Issue #179 - Fix E2E test for check search providers order

- package.json
resolves:  #180
resolves:  PIX-976
> Issue #180 | Move puppeteer to dev dependency

- src/components/options/providers/contextMenuItems.svelte
- src/components/options/settings/importExport.svelte
- src/components/options/settings/main.svelte
pix-1010
#183 
Thanks for @mfgorsuch for helping with the text
> pix-1010 #183 - clarify when MSO is used
